#!/usr/bin/ruby -w


## Add a new device
# addswitch smallname hostname loopback_ip model
# addswitch c01 core1 1.2.3.4 c37560e-15.2

require './i.rb'

smallname, hostname, ip, model = ARGV

sw=Switch.create(smallname, hostname, ip, model)
sw.template
Sql.commit
